### PR TITLE
Add support for PostgreSQL to Dockerfile

### PR DESCRIPTION
**Pull request by snailcatcher**
Hi i would like to contribute my implementation for using postgres as database service.
I also added a small docker-compose example how to use a PostgreSQL database with koel.

Hope you like it.

And thanks to _Ben Petering_ for his investigations:
https://benpetering.com/posts/2020/10/25/php-and-postgres-with-docker.html

### CODE REVIEW

**Comment by snailcatcher** [comment]
Will this be reviewed? Or is the succesful pipeline run enough?

**Comment by Hyzual** [comment]
Hi, thanks for contributing 🙂 ! I'll review it as soon as I get the chance, but I prefer to say in advance, it might be a few days before I can start.
The pipeline does not run docker-compose so it won't be enough to know if it works.

**Comment by Hyzual** [comment]
The Dockerfile and docker-compose.yml file look good to me :+1:

**Comment by Hyzual** [comment]
I've tested with the Dockerfile and the docker-compose file. I can log in but scanning with `php artisan koel:sync -v` crashes on the first song it reads. Does it work on your end ?

```
In Exception.php line 18:
                                                                                                             
  [Doctrine\DBAL\Driver\PDO\Exception (23505)]                                                               
  SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "albums_pkey"  
  DETAIL:  Key (id)=(1) already exists.                                                                      
                                                                                                             

Exception trace:
  at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
 Doctrine\DBAL\Driver\PDO\Exception::new() at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
 Doctrine\DBAL\Driver\PDOStatement->execute() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:343
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
 Illuminate\Database\Connection->runQueryCallback() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:638
 Illuminate\Database\Connection->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:346
 Illuminate\Database\Connection->select() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:316
 Illuminate\Database\Connection->selectFromWriteConnection() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php:24
 Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2882
 Illuminate\Database\Query\Builder->insertGetId() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1560
 Illuminate\Database\Eloquent\Builder->__call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1052
 Illuminate\Database\Eloquent\Model->insertAndSetId() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1017
 Illuminate\Database\Eloquent\Model->performInsert() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:858
 Illuminate\Database\Eloquent\Model->save() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:471
 Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php:263
 tap() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:472
 Illuminate\Database\Eloquent\Builder->firstOrCreate() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:23
 Illuminate\Database\Eloquent\Model->forwardCallTo() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1890
 Illuminate\Database\Eloquent\Model->__call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1902
 Illuminate\Database\Eloquent\Model::__callStatic() at /var/www/html/app/Models/Album.php:79
 App\Models\Album::getOrCreate() at /var/www/html/app/Services/FileSynchronizer.php:199
 App\Services\FileSynchronizer->sync() at /var/www/html/app/Services/MediaSyncService.php:112
 App\Services\MediaSyncService->sync() at /var/www/html/app/Console/Commands/SyncCommand.php:70
 App\Console\Commands\SyncCommand->syncAll() at /var/www/html/app/Console/Commands/SyncCommand.php:48
 App\Console\Commands\SyncCommand->handle() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php:40
 Illuminate\Container\Util::unwrapIfClosure() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:611
 Illuminate\Container\Container->call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:136
 Illuminate\Console\Command->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:121
 Illuminate\Console\Command->run() at /var/www/html/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:290
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:166
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:92
 Illuminate\Console\Application->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/artisan:35
 ```

**Comment by Hyzual** [comment]
It looks like someone else stumbled upon this issue while running koel. Your contribution is fine, but if merging it will only lead to people being blocked because they cannot scan music, I would prefer not to merge it. It's unclear to me whether koel does or does not support postgres 😕

**Comment by vitoyucepi** [comment]
I think the issue won't be fixed in upstream by original author.

**Comment by snailcatcher** [comment]
Hmm, I did not really test this out.
I test to login and navigate the webinterface with the postgreSQL Database in the backend.

It is okay not to merge. This will lead to more issues than necessary.

**Comment by snailcatcher** [comment]
@Hyzual I think i have fixed the issue you had. Could you please test it again.
I tested it in my setup by appling the following to the original container:
```sh
apt-get update && apt-get install -y libpq-dev
docker-php-ext-install pdo pdo_pgsql pgsql
service apache2 restart
```

**Comment by Hyzual** [comment]
Hi @snailcatcher, thanks for the fix. I've tested and it does work ! 😄

Out of all the features I tested, I only had another minor error with upload from the web UI. When I try to drop an .mp3 file in the web UI it looks like it fails (the upload bar is red) and the laravel logs show this error:
```
[2021-05-22 17:33:00] production.ERROR: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database {"userId":1,"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 8 attempt to write a readonly database at /var/www/html/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:442)
[stacktrace]
#0 /var/www/html/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(442): PDOStatement->execute()
#1 /var/www/html/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(125): TeamTNT\\TNTSearch\\Indexer\\TNTIndexer->updateInfoTable()
#2 /var/www/html/vendor/teamtnt/tntsearch/src/TNTSearch.php(457): TeamTNT\\TNTSearch\\Indexer\\TNTIndexer->setStemmer()
#3 /var/www/html/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(54): TeamTNT\\TNTSearch\\TNTSearch->getIndex()
#4 /var/www/html/vendor/laravel/scout/src/Searchable.php(63): TeamTNT\\Scout\\Engines\\TNTSearchEngine->update()
#5 /var/www/html/vendor/laravel/scout/src/Searchable.php(42): App\\Models\\Artist->queueMakeSearchable()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(114): Illuminate\\Database\\Eloquent\\Collection->Laravel\\Scout\\{closure}()
#7 /var/www/html/vendor/laravel/scout/src/Searchable.php(154): Illuminate\\Support\\Collection->__call()
#8 /var/www/html/vendor/laravel/scout/src/ModelObserver.php(87): App\\Models\\Song->searchable()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412): Laravel\\Scout\\ModelObserver->saved()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\\Events\\Dispatcher->dispatch()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(899): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(870): Illuminate\\Database\\Eloquent\\Model->finishSave()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(485): Illuminate\\Database\\Eloquent\\Model->save()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(486): tap()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->updateOrCreate()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1890): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1902): Illuminate\\Database\\Eloquent\\Model->__call()
#20 /var/www/html/app/Services/FileSynchronizer.php(209): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#21 /var/www/html/app/Services/MediaSyncService.php(112): App\\Services\\FileSynchronizer->sync()
#22 /var/www/html/app/Http/Controllers/API/SettingController.php(26): App\\Services\\MediaSyncService->sync()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\API\\SettingController->store()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#29 /var/www/html/app/Http/Middleware/Authenticate.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Authenticate->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(63): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /var/www/html/app/Http/Middleware/ForceHttps.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ForceHttps->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#58 /var/www/html/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle()
#59 {main}
"}
```

The upload did go through though (the song can be played), but it looks like there is some SQL error with the TNTSearch feature.

I don't consider this blocking as there is the workaround of adding files in the docker volume "by hand" and scanning them with `php artisan koel:sync` and/or with `php artisan koel:search:import`. I could open an issue in koel/koel if you want.

I haven't tested every feature of Koel but the most prominent ones all work properly 😄. Thanks for the contribution, I'll squash the commits and merge the pull request. I'll edit the README to document the support for Postgres too.

**Comment by Hyzual** [comment]
For the record I have the same problem with upload on MySQL...

**Comment by LeducH** [comment]
> @Hyzual I think i have fixed the issue you had. Could you please test it again.
> I tested it in my setup by appling the following to the original container:
> 
> ```shell
> apt-get update && apt-get install -y libpq-dev
> docker-php-ext-install pdo pdo_pgsql pgsql
> service apache2 restart
> php artisan koel:init
> ```

good man

**Pull request closed without merging**
